version: '3.6'

services:
  credentials:
    image: jesusgoku/spotify-backup:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: ./.env
    entrypoint: /bin/credentials

  backup:
    image: jesusgoku/spotify-backup:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: ./.env
    entrypoint: /bin/backup

